apiVersion: batch/v1
kind: Job
metadata:
  name: loadgen
  namespace: demo
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: curl
        image: curlimages/curl:8.8.0
        command:
          - /bin/sh
          - -c
          - |
            i=0
            while [ $i -lt 400 ]; do
              curl -s -o /dev/null -H "Host: app.127.0.0.1.nip.io" \
              http://ingress-ingress-nginx-controller.ingress-nginx.svc/
              i=$((i+1))
            done
            echo done
