apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: demo
type: Opaque
stringData:
  DATABASE_URL: postgresql://appuser:NvUMiIEuwctVra1KBlqp@postgres.demo.svc.cluster.local:5432/appdb
